<?xml version="1.0"?>
<robot name="forklift" xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- PARAMETERS-->

	<!-- Hokuyo Laser scanner -->
	<xacro:property name="hokuyo_size" value="0.05" />

	<!-- PROPERTY LIST -->
	<!--All units in m-kg-s-radians unit system -->
	<xacro:property name="M_PI" value="3.1415926535897931" />
	<xacro:property name="M_PI_2" value="1.570796327" />
	<xacro:property name="DEG_TO_RAD" value="0.017453293" />

	<!-- Main body radius and height -->
	<!-- Main Body Cylinder base   -->
	<xacro:property name="base_height" value="0.02" />
	<xacro:property name="base_radius" value="0.15" />
	<xacro:property name="base_mass" value="5" /> <!-- in kg-->


	<!-- main chasis part-->
	<link name="base_link">
		<visual>
			<origin rpy="1.57075 0 -1.57075" xyz="1.375 0.383 0" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/main_chasis.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="green">
				<color rgba="0.3 1 0.3 1" />
			</material>
		</visual>

		<!-- main chasis collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 -1.57075" xyz="1.375 0.383 0" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/main_chasis.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="5" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<!-- column part -->
	<link name="column">
		<visual>
			<!--<origin rpy="1.57075 0 1.57075 " xyz="-0.073 -0.098 -0.25" />-->
			<origin rpy="0 0 1.57075" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/column.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.6" radius="0.045"/>
			</geometry>
			<material name="grey">
				<color rgba="0.1 0 1 0.8" />
			</material>
		</visual>

		<!-- column collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 1.57075 " xyz="-0.073 -0.098 -0.25" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/column.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.6" radius="0.045"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="2" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<!-- main chasis + column joining-->
	<joint name="steering_joint" type="continuous">
		<axis xyz="0 0 1" />
		<!--<limit effort="1000.0" lower="-1.57075" upper="1.57075" velocity="0.5" />-->
		<parent link="base_link" />
		<child link="column" />
		<!--<origin xyz="0 0 0.5" />-->
		<origin xyz="0 0 0.5" />
	</joint>

	<!-- wheel mounting part-->
	<link name="mounting_wheel">
		<visual>
			<origin rpy="1.57075 0 1.57075" xyz="-0.073 -0.107 -0.14" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/mount_wheel.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.3 1 0.3 1" />
			</material>
		</visual>

		<!-- wheel collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 1.57075" xyz="-0.073 -0.107 -0.14" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/mount_wheel.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="column_to_mounting_wheel" type="fixed">
		<parent link="column" />
		<child link="mounting_wheel" />
		<origin xyz="0 0 -0.3" />
	</joint>

	<!-- driving motor part-->
	<link name="motor">
		<visual>
			<origin rpy="1.57075 0 1.57075" xyz="-0.068 -0.045 -0.07" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/driving_motor.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.3 0.3 0.3 0.5" />
			</material>
		</visual>

		<!-- driving motor collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 1.57075" xyz="-0.068 -0.045 -0.07" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/driving_motor.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="2" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="mounting_wheel_to_motor" type="fixed">
		<parent link="mounting_wheel" />
		<child link="motor" />
		<origin xyz="0 0 -0.08" />
	</joint>

	<!-- driving wheel part-->
	<link name="driving_wheel">
		<visual>
			<!--<origin rpy="0 0 1.57075" xyz="0.125 -0.044 -0.125" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/driving_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.155"/>
			</geometry>
			<material name="grey">
				<color rgba="0.3 0.3 0.3 1" />
			</material>
		</visual>
		<!-- driving collision, mass and inertia -->
		<collision>
			<origin rpy="0 0 1.57075" xyz="0.125 -0.044 -0.125" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/driving_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.155"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="2" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="driving_joint" type="continuous">
		<axis xyz="0 1 0" />
		<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
		<parent link="motor" />
		<child link="driving_wheel" />
		<origin xyz="0 0 0" />
	</joint>

	<!-- fork mount part-->
	<link name="fork_mount">
		<visual>
			<origin rpy="1.57075 0 0 " xyz="0 0.54 0.1" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/fork_holder.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.1 0 1 1" />
			</material>
		</visual>

		<!-- fork mount collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 0 " xyz="0 0.54 0.1" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/fork_holder.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="2" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="fork_joint" type="prismatic">
		<axis xyz="0 0 1" />
		<limit effort="1000.0" lower="0" upper="1.4" velocity="0.5" />
		<parent link="base_link" />
		<child link="fork_mount" />
		<origin xyz="0.45 0 0" />
	</joint>

	<!-- left fork part-->
	<link name="fork_left">
		<visual>
			<origin rpy="1.57075 0 0" xyz="-0.02 0.08 -0.41" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/fork.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.3 0.3 0.3 1" />
			</material>
		</visual>

		<!-- left fork collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 0" xyz="-0.02 0.08 -0.41" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/fork.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="2" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="fork_left_left" type="fixed">
		<parent link="fork_mount" />
		<child link="fork_left" />
		<origin xyz="0.13 0.25 0.47" />
	</joint>

	<!-- right fork part-->
	<link name="fork_right">
		<visual>
			<origin rpy="1.57075 0 0" xyz="-0.02 0.08 -0.41" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/fork.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.13 0.3 0.3 1" />
			</material>
		</visual>

		<!-- left fork collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 0" xyz="-0.02 0.08 -0.41" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/fork.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="2" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="fork_right_right" type="fixed">
		<parent link="fork_mount" />
		<child link="fork_right" />
		<origin xyz="0.13 -0.25 0.47" />
	</joint>

	<!-- FR wheel part-->
	<link name="FR_wheel">
		<visual>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- front collision, mass and inertia -->
		<collision>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="FR_joint" type="continuous">
		<axis xyz="0 1 0" />
		<!--<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />-->
		<parent link="base_link" />
		<child link="FR_wheel" />
		<!--<origin xyz="1.32 -0.29 0.02" />-->
		<origin xyz="1.32 -0.26 0.02" />
	</joint>

	<!-- RR wheel part-->
	<link name="RR_wheel">
		<visual>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- front collision, mass and inertia -->
		<collision>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<!-- main chasis + RR wheel joining-->
	<joint name="RR_joint" type="continuous">
		<axis xyz="0 1 0" />
		<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
		<parent link="base_link" />
		<child link="RR_wheel" />
		<!--<origin xyz="1.32 -0.29 0.02" />-->
		<origin xyz="1.23 -0.26 0.02" />
	</joint>

	<!-- FL wheel part-->
	<link name="FL_wheel">
		<visual>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- front collision, mass and inertia -->
		<collision>
			<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="FL_joint" type="continuous">
		<axis xyz="0 1 0" />
		<!--<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />-->
		<parent link="base_link" />
		<child link="FL_wheel" />
		<!--<origin xyz="1.32 0.235 0.02" />-->
		<origin xyz="1.32 0.26 0.02" />
	</joint>

	<!-- RL wheel part-->
	<link name="RL_wheel">
		<visual>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- front collision, mass and inertia -->
		<collision>
			<!--<origin rpy="0 1.57075 1.57075" xyz="0.04 0 0.04" />-->
			<origin rpy="1.57075 0 0" xyz="0 0 0" />
			<geometry>
				<!--<mesh filename="package://forklift_sim/meshes/front_wheel.STL" scale="0.001 0.001 0.001" />-->
				<cylinder length="0.06" radius="0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="RL_joint" type="continuous">
		<axis xyz="0 1 0" />
		<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5" />
		<parent link="base_link" />
		<child link="RL_wheel" />
		<origin xyz="1.23 0.26 0.02" />
	</joint>

	<!-- Accesories part-->
	<!-- Casing-->
	<link name="casing">
		<visual>
			<origin rpy="1.57075 0 -1.57075" xyz="1.8 0.528 -0.68" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/casing.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- casing collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 -1.57075" xyz="1.8 0.528 -0.68" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/casing.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="0.5" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="main_chasis_to_casing" type="fixed">
		<parent link="base_link" />
		<child link="casing" />
		<origin xyz="-0.1 0 0.6" />
	</joint>

	<!-- Casing battery-->
	<link name="casing_battery">
		<visual>
			<origin rpy="1.57075 0 -1.57075" xyz="1.58 0.528 -0.68" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/casing_battery.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- casing collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 -1.57075" xyz="1.58 0.528 -0.68" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/casing_battery.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="0.5" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="main_chasis_to_casing_battery" type="fixed">
		<parent link="base_link" />
		<child link="casing_battery" />
		<origin xyz="0.1 0 0.6" />
	</joint>

	<!-- Casing bottom lidar-->
	<link name="lower_lidar_mount">
		<visual>
			<origin rpy="1.57075 0 -1.57075" xyz="1.99 0.53 -0.08" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/lower_lidar_mount.STL" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="grey">
				<color rgba="0.35 0.3 0.3 1" />
			</material>
		</visual>

		<!-- lower lidar mount collision, mass and inertia -->
		<collision>
			<origin rpy="1.57075 0 -1.57075" xyz="1.99 0.53 -0.08" />
			<geometry>
				<mesh filename="package://forklift_sim/meshes/lower_lidar_mount.STL" scale="0.001 0.001 0.001" />
			</geometry>
		</collision>
		<inertial>
			<mass value="1" />
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13" />
		</inertial>
	</link>

	<joint name="main_chasis_to_lower_lidar_mount" type="fixed">
		<parent link="base_link" />
		<child link="lower_lidar_mount" />
		<origin xyz="-0.31 0 0" />
	</joint>


	<!-- SENSORS -->

	<!-- hokuyo -->
	<link name="hokuyo_link">
		<visual>
			<origin xyz="0 0 0.03" rpy="0 0 0" />
			<geometry>
				<box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}" />
			</geometry>
			<material name="Blue" />
		</visual>
	</link>

	<!-- main chasis + lower lidar mount joining-->
	<joint name="lower_lidar" type="fixed">
		<parent link="lower_lidar_mount" />
		<child link="hokuyo_link" />
		<origin xyz="0 0 0.15" rpy="0 0 3.1415"/>
	</joint>

	<!-- calling parts in gazebo-->
	<!-- lidar calling in gazebo-->
	<gazebo reference="hokuyo_link">
		<material>Gazebo/Blue</material>
		<turnGravityOff>false</turnGravityOff>
		<sensor type="ray" name="head_hokuyo_sensor">
			<pose>${hokuyo_size/2} 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>40</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>720</samples>
						<resolution>1</resolution>
						<min_angle>-1.5</min_angle>
						<max_angle>1.5</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.10</min>
					<max>10.0</max>
					<resolution>0.001</resolution>
				</range>
			</ray>
			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
				<topicName>/scan</topicName>
				<frameName>hokuyo_link</frameName>
			</plugin>
		</sensor>
	</gazebo>

	
	<!-- main chasis calling in gazebo-->
	<gazebo reference="base_link">
		<material>Gazebo/Grey</material>
		<pose>0 0 3 0 0 0</pose>
	</gazebo>
	
	<gazebo reference="column">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<gazebo reference="mounting_wheel">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<gazebo reference="motor">
		<material>Gazebo/Grey</material>
	</gazebo>
	
	<gazebo reference="driving_wheel">
		<material>Gazebo/Yellow</material>
	</gazebo>
	
	<gazebo reference="fork_mount">
		<material>Gazebo/Gray</material>
	</gazebo>
	
	<gazebo reference="fork_left">
		<material>Gazebo/Gray</material>
	</gazebo>
	
	<gazebo reference="fork_right">
		<material>Gazebo/Gray</material>
	</gazebo>
	
	<gazebo reference="FR_wheel">
		<material>Gazebo/Yellow</material>
	</gazebo>
	
	<gazebo reference="RR_wheel">
		<material>Gazebo/Yellow</material>
	</gazebo>
	
	<gazebo reference="FL_wheel">
		<material>Gazebo/Yellow</material>
	</gazebo>
	
	<gazebo reference="RL_wheel">
		<material>Gazebo/Yellow</material>
	</gazebo>
	
	<gazebo reference="casing">
		<material>Gazebo/Green</material>
	</gazebo>
	
	<gazebo reference="casing_battery">
		<material>Gazebo/Green</material>
	</gazebo>
	
	<gazebo reference="lower_lidar_mount">
		<material>Gazebo/Grey</material>
	</gazebo>-->

	<!-- This tag function connects the non fixed part joint to an actuator (motor), which informs both simulation and visualization of the robot -->
	<transmission name="steering_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="steering_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="steering_joint">
			<!-- refer to the name joint-->
			<hardwareInterface>PositionJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<transmission name="driving_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="driving_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="driving_joint">
			<!-- refer to the name joint-->
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<transmission name="fork_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="fork_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="fork_joint">
			<!-- refer to the name joint-->
			<hardwareInterface>PositionJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<transmission name="FR_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="FR_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="FR_joint"> <!-- refer to the name joint-->
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<transmission name="FL_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="FL_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="FL_joint"><!-- refer to the name joint-->
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<transmission name="RR_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="RR_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="RR_joint"><!-- refer to the name joint-->
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<transmission name="RL_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<actuator name="RL_motor">
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
		<joint name="RL_joint"> <!-- refer to the name joint-->
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
	</transmission>

	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/</robotNamespace>
		</plugin>
	</gazebo>

</robot>
